# Generated by Django 3.0.4 on 2020-03-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.IntegerField()),
                ('bacon', models.IntegerField()),
                ('cheese', models.IntegerField()),
                ('meat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('salad', models.IntegerField()),
                ('bacon', models.IntegerField()),
                ('cheese', models.IntegerField()),
                ('meat', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('deliveryMethod', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
